name: pip build windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Build wheels for Python
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        run: |
          set VCPKG_BUILD_TYPE=release
          vcpkg install yasm-tool:x86-windows
          vcpkg install eigen3 cgal --triplet x64-windows
          dir C:/vcpkg/installed/x64-windows/bin

# -DGMP_INCLUDE_DIR="c:/vcpkg/installed/x64-windows/include" -DGMP_LIBRARIES="c:/vcpkg/installed/x64-windows/bin/gmp.dll" -DGMP_LIBRARIES_DIR="c:/vcpkg/installed/x64-windows/bin"
      - name: Build python wheel
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="c:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows ..
          cp  c:/vcpkg/installed/x64-windows/bin/mpfr-6.dll .
          cp  c:/vcpkg/installed/x64-windows/bin/gmp.dll .
