name: pip build windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Build wheels for Python
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install vcpkg and packages
        uses: lukka/run-vcpkg@v6
        with:
          # vcpkg 2021.04.30
          vcpkgGitCommitId: 44d94c2edbd44f0c01d66c2ad95eb6982a9a61bc
          setupOnly: true
      # Now that vcpkg is installed, it is being used to run with the desired arguments.
      - run: |
          $VCPKG_ROOT/vcpkg install yasm-tool:x86-windows
          $VCPKG_ROOT/vcpkg install eigen3:x64-windows cgal:x64-windows
      - name: Install dependencies
        run: |
          type c:/vcpkg/ports/cgal/portfile.cmake
          dir C:/vcpkg/installed/x64-windows/bin
          type C:/vcpkg/installed/x64-windows/include/CGAL/version.h

# -DGMP_INCLUDE_DIR="c:/vcpkg/installed/x64-windows/include" -DGMP_LIBRARIES="c:/vcpkg/installed/x64-windows/bin/gmp.dll" -DGMP_LIBRARIES_DIR="c:/vcpkg/installed/x64-windows/bin"
      - name: Build python wheel
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="c:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows ..
          cp  c:/vcpkg/installed/x64-windows/bin/mpfr-6.dll .
          cp  c:/vcpkg/installed/x64-windows/bin/gmp.dll .
