name: pip build windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8']
    name: Build wheels for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          cd c:/vcpkg
          git checkout 2020.11
          bootstrap-vcpkg.bat
          copy triplets\x64-windows.cmake triplets\x64-windows-release.cmake
          echo "set(VCPKG_BUILD_TYPE release)" >> triplets\x64-windows-release.cmake
          vcpkg install gmp eigen3 cgal --triplet x64-windows-release
      - name: Build python wheel
        run: |
          dir c:/vcpkg/installed/x64-windows-release/bin/
          cp  c:/vcpkg/installed/x64-windows-release/bin/mpfr.dll .
          cp  c:/vcpkg/installed/x64-windows-release/bin/mpir.dll .
