name: pip build windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Build wheels for Python
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        run: |
#          vcpkg version
          cd c:
          git clone --depth 1 --branch 2020.11 https://github.com/microsoft/vcpkg vcpkgbis
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg version
#          copy triplets\x64-windows.cmake triplets\x64-windows-release.cmake
#          echo "set(VCPKG_BUILD_TYPE release)" >> triplets\x64-windows-release.cmake
#          vcpkg install eigen3 cgal --triplet x64-windows-release
#      - name: Build python wheel
#        run: |
#          mkdir build
#          cd build
#          cmake -DCMAKE_BUILD_TYPE=Release -DGMP_INCLUDE_DIR="c:/vcpkgbis/installed/x64-windows-release/include" -DGMP_LIBRARIES="c:/vcpkgbis/installed/x64-windows-release/lib/mpir.lib" -DGMP_LIBRARIES_DIR="c:/vcpkgbis/installed/x64-windows-release/lib" -DCMAKE_TOOLCHAIN_FILE="c:/vcpkgbis/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-release ..
#          cp  c:/vcpkgbis/installed/x64-windows-release/bin/mpfr.dll .
#          cp  c:/vcpkgbis/installed/x64-windows-release/bin/mpir.dll .
