name: pip build windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Build wheels for Python
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        run: |
          cd c:/vcpkg
          git fetch --all --tags
          git checkout 2020.11-1
          bootstrap-vcpkg.bat
          set VCPKG_BUILD_TYPE=release
          vcpkg install eigen3 mpfr boost-accumulators boost-algorithm boost-bimap boost-callable-traits boost-concept-check boost-container boost-core boost-detail boost-filesystem boost-functional boost-fusion boost-geometry boost-graph boost-heap boost-intrusive boost-iostreams boost-iterator boost-lambda boost-logic boost-math boost-mpl boost-multi-index boost-multiprecision boost-numeric-conversion boost-optional boost-parameter boost-pool boost-preprocessor boost-property-map boost-property-tree boost-ptr-container boost-random boost-range boost-serialization boost-spirit boost-thread boost-tuple boost-type-traits boost-units boost-utility boost-variant --triplet x64-windows
          vcpkg version
          dir C:/vcpkg/installed/x64-windows/bin
          cd ${{ github.workspace }}
          Invoke-WebRequest https://github.com/CGAL/cgal/releases/download/v5.2.1/CGAL-5.2.1.zip -OutFile CGAL-5.2.1.zip
          Expand-Archive -Path CGAL-5.2.1.zip -DestinationPath .

      - name: Build python wheel
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCGAL_DIR=../CGAL-5.2.1 -DCMAKE_TOOLCHAIN_FILE="c:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DGMP_INCLUDE_DIR="c:/vcpkg/installed/x64-windows/include" -DGMP_LIBRARIES="c:/vcpkg/installed/x64-windows/bin/gmp.dll" -DGMP_LIBRARIES_DIR="c:/vcpkg/installed/x64-windows/bin" ..
          cp  c:/vcpkg/installed/x64-windows/bin/mpfr-6.dll .
          cp  c:/vcpkg/installed/x64-windows/bin/gmp.dll .
