name: pip build windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8']
    name: Build wheels for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          vcpkg update
          vcpkg upgrade --no-dry-run
          type c:/vcpkg/ports/cgal/portfile.cmake
          vcpkg install yasm-tool eigen3 mpfr mpir cgal --triplet x64-windows
      - name: Build python wheel
        run: |
          mkdir build
          cd build
          dir c:/vcpkg/installed/x64-windows/bin/
          cp c:/vcpkg/installed/x64-windows/bin/mpfr.dll .
          cp c:/vcpkg/installed/x64-windows/bin/mpir.dll .
